name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Set to your project's .NET version

      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore

      - name: Check code formatting
        working-directory: ./src
        run: dotnet format --verify-no-changes --severity error

      - name: Build (fail on warnings)
        working-directory: ./src
        run: dotnet build --no-restore --configuration Release -warnaserror

      - name: Run tests
        working-directory: ./src
        run: dotnet test --no-build --verbosity normal
